#!/bin/bash
#
#

EXIT_OK=0
EXIT_FAIL=1
EXIT_FILE_EXISTS=2
EXIT_BAD_PARAMS=3

ARCHIVE_FOLDER=~/WAL_ARCHIVES

# Sanity checks
if [[ "$#" -ne 2 ]]; then
    exit ${EXIT_BAD_PARAMS}
fi

mkdir -p ${ARCHIVE_FOLDER}
chmod 700 ${ARCHIVE_FOLDER}

SRC_FILENAME=$1
WAL_FILENAME=$2


# copy file but dont overwrite existing one
if [[ -f ${ARCHIVE_FOLDER}/${WAL_FILENAME} ]]; then
    echo "${WAL_FILENAME} alreday exists in ${ARCHIVE_FOLDER}" >&2
    exit ${EXIT_FILE_EXISTS}
else 
    cp -p ${SRC_FILENAME} ${ARCHIVE_FOLDER}/${WAL_FILENAME}
    exit $?
fi

exit ${EXIT_OK}

